### ISSUE TITLE
No results returned - Quora page structure changed?

### ISSUE THREAD

**Issue by richierichGIT** [Theminijohn/quora-scraper#2]
Hi! 

I've got it running but the resulting .csv only has the headers and no results, any ideas?

**Comment by Theminijohn** [comment]
Hey @richierichGIT, sorry just saw this 😅

Worked for me just fine now, updated the `followers_count` to the new selector quora switched to.
If you're on a topic, make sure that you click `All Questions` in the topic options.

<img width="635" alt="Screenshot 2019-08-12 at 19 53 07" src="https://user-images.githubusercontent.com/2203679/62890190-d755fb80-bd3a-11e9-9fb0-bbe554d437e8.png">

Let me know if you still have problems
