### ISSUE TITLE
This is a good idea...but it needs more automation.

### ISSUE THREAD

**Issue by slapheadted** [Theminijohn/quora-scraper#3]
Have you considered removing the manual requirement of downloading the web pages? This idea could be drastically improved if users could enter strings to direct the program to do its own scraping (via user-interaction simulation tool).

**Comment by Theminijohn** [comment]
Hey @slapheadted, 

actually yes :) My Internal tool does that automatically via selenium & a headless browser. This would severely bump the set up difficulty tho and this was intended for marketers, not developers. 

Are you interested in a solution like this? You can get notified here when it launches: https://docs.google.com/forms/d/17iK75u5w9OPt7PPvMCX9nXeVLhxEjYGarGAUpcH2tQ0
