### ISSUE TITLE
running on windows - input.htm not found

### ISSUE THREAD

**Issue by K3nn3th2** [Theminijohn/quora-scraper#4]
Hey there,

i'm trying to run your scraper in Windows.
I followed your instructions but ended up with an error saying 'pry' was not found.
After installing the 'pry' gem I got the following error:

`scraper.rb:15:in 'initialize': No such file or directory @ rb_sysopen - input.htm (Errno::ENOENT)
`
I then renamed the downloaded HTML file to input.htm but the error keeps appearing.
It lives in the same directory as the scraper.rb script.

Any ideas?

**Comment by Theminijohn** [comment]
Hey @K3nn3th2, sorry for the delay here 😅

That probably happens because you don't have `input.htm` in the same folder as the script. Do you still experience this issue?
