### ISSUE TITLE
Unable to pull >20 results

### ISSUE THREAD

**Issue by tobygibbs** [Theminijohn/quora-scraper#5]
Hey John,

Great tool although I can't seem to pull more than 20 results, regardless of the amount of scrolling.

Have Quora changed something their end perhaps?

KR,

Toby

**Comment by Theminijohn** [comment]
Hey Toby,

I just checked and I'm getting definitely more than 20 results. The more I scroll the more I get.

Do you use cmd/ctrl + S to save the whole page?

**Comment by tobygibbs** [comment]
Thanks for getting back to me John.

I had an issue saving the HTML, couldn't work out what I was doing wrong.

The chrome plugin I used to save the HTML is called "Save Page WE" (no affiliation). I had found a few others that were having the same issue so I hope this helps someone in the future.

Great tool, thank you for sharing it with me.

KR

Toby

**Comment by Theminijohn** [comment]
Try using cmd/ctrl + S directly. Shouldn't need any other tools for that!

Glad you found it useful, let me know if you need any help ✌️
